---
  - name: Clear log
    local_action: shell tail -20 /var/log/ansible.log | sed -e "s/.* |//g" | sed -e "s/*//g" | sed -e "s/   / /g" | sed -e "s/  / /g" > /var/log/ansible-bot.log
    tags:
      - always
  - name: send a message to chat in playbook
    telegram:
      token: ''
      chat_id: ''
      msg: "done {{lookup('file', '/var/log/ansible-bot.log') }}"
