---
- name: Install utils for docker"
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  tags:
    - install_docker
    - deploy


- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  tags:
    - install_docker
    - deploy
- name: Install Docker
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce-18.09.1
    - containerd.io
  tags:
    - install_docker
    - deploy

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - install_docker
    - deploy
